---
name: RIF Marketplace PINNER DEVELOP deploy

on:
  push:

    branches:
      - develop

jobs:
  deploy-develop:
    name: RIF Marketplace PINNER - Develop
    runs-on: ubuntu-latest
    environment:
      name: develop

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEVELOP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEVELOP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEVELOP_AWS_REGION }}


      - name: Deploy rif-marketplace-pinner develop
        run: |
          aws ssm send-command \
              --document-name "AWS-RunRemoteScript" \
              --targets '[{"Key":"InstanceIds","Values":["${{ secrets.DEVELOP_EC2_ID_1 }}","${{ secrets.DEVELOP_EC2_ID_2 }}"]}]' \
              --region=${{ secrets.DEVELOP_AWS_REGION }} \
              --comment "github interaction-rif-marketplace-pinner" \
              --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"rootstock\", \"repository\":\"ask-devops\", \"path\": \"rif-marketplace/\",\"tokenInfo\":\"{{ssm-secure:github-token}}\"}"],"commandLine":["deploy-marketplace-pinner-dev.sh"]}'

