---
name: RIF Marketplace PINNER TESTNET deploy

on:
  push:
    branches:
      - testnet

jobs:
  deploy-testnet:
    name: RIF Marketplace PINNER - Testnet
    runs-on: ubuntu-latest
    environment:
      name: testnet

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TESTNET_AWS_REGION }}


      - name: Deploy rif-marketplace-pinner testnet
        run: |
          aws ssm send-command \
              --document-name "AWS-RunRemoteScript" \
              --targets '[{"Key":"InstanceIds","Values":["${{ secrets.TESTNET_EC2_ID_1 }}","${{ secrets.TESTNET_EC2_ID_2 }}"]}]' \
              --region=${{ secrets.STAGING_AWS_REGION }} \
              --comment "github interaction-rif-marketplace-pinner" \
              --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"rootstock\", \"repository\":\"ask-devops\", \"path\": \"rif-marketplace/\",\"tokenInfo\":\"{{ssm-secure:github-token}}\"}"],"commandLine":["deploy-marketplace-pinner-testnet.sh"]}'

